import { describe, it, expect, vi, beforeEach, afterEach } from 'vitest';
import { flushPromises, mount } from '@vue/test-utils';
import { nextTick } from 'vue';
import { createTestRouter, createTestI18n } from '../../__tests__/helpers/test-utils';

let messageHandlers: Array<(event: MessageEvent) => void> = [];
let vscodeApiMock: {
  postMessage: ReturnType<typeof vi.fn>;
  getState: ReturnType<typeof vi.fn>;
  setState: ReturnType<typeof vi.fn>;
};

beforeEach(() => {
  messageHandlers = [];
  vscodeApiMock = {
    postMessage: vi.fn(),
    getState: vi.fn(() => undefined),
    setState: vi.fn(),
  };
  (window as unknown as { acquireVsCodeApi: () => typeof vscodeApiMock }).acquireVsCodeApi = () => vscodeApiMock;
  vi.spyOn(window, 'addEventListener').mockImplementation((type, listener) => {
    if (type === 'message') {
      messageHandlers.push(listener as (event: MessageEvent) => void);
    }
  });
});

afterEach(() => {
  messageHandlers = [];
  vi.restoreAllMocks();
  vi.clearAllMocks();
});

function dispatchMessage(message: unknown) {
  const event = new MessageEvent('message', { data: message });
  messageHandlers.forEach((handler) => handler(event));
}

async function createState() {
  vi.resetModules();
  const mod = await import('../../composables/useAppState');
  const { appRouterKey } = await import('../../composables/useAppRouter');
  const router = createTestRouter();
  const i18n = createTestI18n();
  const wrapper = mount(
    {
      template: '<div></div>',
      setup() {
        const state = mod.useAppState();
        return { state };
      },
    },
    { global: { plugins: [router, i18n], provide: { [appRouterKey]: router } } },
  );
  await flushPromises();
  return { wrapper, state: wrapper.vm.state as ReturnType<typeof mod.useAppState> };
}

type AppState =
  ReturnType<typeof createState> extends Promise<infer T> ? (T extends { state: infer S } ? S : never) : never;

/** The server the webview is configured against first. */
const INSTANCE_A = {
  id: 'inst-a',
  url: 'https://forgejo.example.com/alpha',
  name: 'alpha-user@forgejo.example.com',
  username: 'alpha-user',
};

/** The replacement: same id, different URL, so the identity changed. */
const REPLACED = { ...INSTANCE_A, url: 'https://forgejo.example.com/beta' };

function repo(id: number, name: string) {
  return { id, name, full_name: `owner/${name}` } as never;
}

/**
 * The opaque id of the last request this webview posted for one list's command.
 *
 * The ids are generated by the webview, so a test has to read them back out of
 * the posts to answer with the id the request actually carried — that echo is
 * exactly what the host sends and what attribution now reads.
 */
function listRequestId(command: string): string | undefined {
  const calls = vscodeApiMock.postMessage.mock.calls.filter(
    ([message]) => (message as { command?: string } | undefined)?.command === command,
  );
  return (calls.at(-1)?.[0] as { _requestId?: string } | undefined)?._requestId;
}

/**
 * One dashboard list's reply path: the key its loading slot uses, the command
 * that asks for it, and a reply carrying rows. Each row carries a `name`/`title`
 * — the marker the assertions key on — so the three lists are checked the same
 * way. `reply` echoes the request id under test, and omits it entirely when the
 * caller passes none (the older-host / failure-without-id shape).
 */
const LISTS = [
  {
    label: 'repositories',
    key: `repos-${INSTANCE_A.id}`,
    request: { command: 'getRepositories', instanceId: INSTANCE_A.id },
    reply: (server: 'old' | 'new', requestId?: string) => ({
      command: 'repositories',
      instanceId: INSTANCE_A.id,
      repositories: [repo(server === 'old' ? 1 : 2, server === 'old' ? 'old-server-row' : 'new-server-row')],
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    failure: (error: string, requestId?: string) => ({
      command: 'repositories',
      instanceId: INSTANCE_A.id,
      error,
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    stored: (state: AppState) => state.repositories.value.get(INSTANCE_A.id),
    cached: (state: AppState) => state.repositoriesCache.get(INSTANCE_A.id),
  },
  {
    label: 'my issues',
    key: `issues-${INSTANCE_A.id}-open`,
    request: { command: 'getMyIssues', instanceId: INSTANCE_A.id, state: 'open' },
    reply: (server: 'old' | 'new', requestId?: string) => ({
      command: 'myIssues',
      instanceId: INSTANCE_A.id,
      state: 'open',
      issues: [
        {
          id: server === 'old' ? 1 : 2,
          number: 1,
          title: server === 'old' ? 'old-server-row' : 'new-server-row',
        },
      ],
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    failure: (error: string, requestId?: string) => ({
      command: 'myIssues',
      instanceId: INSTANCE_A.id,
      state: 'open',
      error,
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    stored: (state: AppState) => state.myIssues.value.get(INSTANCE_A.id) as Array<{ title?: string }> | undefined,
    cached: (state: AppState) =>
      state.myIssuesCache.get(`${INSTANCE_A.id}:open`) as Array<{ title?: string }> | undefined,
  },
  {
    label: 'my pull requests',
    key: `pulls-${INSTANCE_A.id}-open`,
    request: { command: 'getMyPullRequests', instanceId: INSTANCE_A.id, state: 'open' },
    reply: (server: 'old' | 'new', requestId?: string) => ({
      command: 'myPullRequests',
      instanceId: INSTANCE_A.id,
      state: 'open',
      pullRequests: [
        {
          id: server === 'old' ? 1 : 2,
          index: 1,
          title: server === 'old' ? 'old-server-row' : 'new-server-row',
        },
      ],
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    failure: (error: string, requestId?: string) => ({
      command: 'myPullRequests',
      instanceId: INSTANCE_A.id,
      state: 'open',
      error,
      ...(requestId !== undefined ? { _requestId: requestId } : {}),
    }),
    stored: (state: AppState) => state.myPullRequests.value.get(INSTANCE_A.id) as Array<{ title?: string }> | undefined,
    cached: (state: AppState) =>
      state.myPullRequestsCache.get(`${INSTANCE_A.id}:open`) as Array<{ title?: string }> | undefined,
  },
] as const;

/** The row marker of a stored/cached list, whichever list it is. */
function rowName(rows: unknown[] | undefined): string | undefined {
  const row = rows?.[0] as { name?: string; title?: string } | undefined;
  return row?.name ?? row?.title;
}

/**
 * An instance edit keeps the id, so the previous server's request is still on
 * the wire when the identity change re-issues the same list for the server now
 * configured. The two replies are identical apart from their payload, so
 * attribution has to come from the request id each one echoes: the record of the
 * request it names decides, whatever order the two replies arrive in. Judging a
 * reply by the oldest queued record instead let the replaced server's reply
 * match the reload's identity/epoch and write its rows — and its cache — under
 * the id the new configuration uses, where they stayed on screen when they
 * landed after the fresh reply.
 */
describe.each(LISTS)('$label reply attribution across an identity change', (list) => {
  /**
   * The live race: the list the user is looking at is being loaded from the
   * server that is about to be replaced, and the replacement's own reload (which
   * `instances` issues) therefore puts two requests for the same key on the
   * wire — one for each server. Returns the id of the superseded request.
   */
  async function startReplacedLoad(state: AppState): Promise<string | undefined> {
    dispatchMessage({ command: 'instances', data: [INSTANCE_A] });
    await nextTick();
    vscodeApiMock.postMessage.mockClear();
    state.loadRepositories(INSTANCE_A.id, true);
    state.loadMyIssues(INSTANCE_A.id, 'open', true);
    state.loadMyPullRequests(INSTANCE_A.id, 'open', true);
    expect(vscodeApiMock.postMessage).toHaveBeenCalledWith(expect.objectContaining(list.request));
    return listRequestId(list.request.command);
  }

  /** Returns the id of the reload's own request, for the server now configured. */
  async function replaceInstance(): Promise<string | undefined> {
    dispatchMessage({ command: 'instances', data: [REPLACED] });
    await nextTick();
    // The identity change re-issues every list for the server now configured, so
    // each key has one outstanding request per server.
    expect(vscodeApiMock.postMessage).toHaveBeenCalledWith(expect.objectContaining(list.request));
    return listRequestId(list.request.command);
  }

  it('names every list request with an opaque id the reply can echo', async () => {
    // The whole attribution rule rests on the two requests for one slot being
    // distinguishable: an edit keeps the instance id, so `instanceId` (and the
    // echoed `state`) cannot tell the replaced server's request from the reload's.
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    expect(typeof supersededId).toBe('string');

    const reloadId = await replaceInstance();
    expect(typeof reloadId).toBe('string');
    expect(reloadId).not.toBe(supersededId);
  });

  it('drops the replaced server’s reply and keeps the reload’s own', async () => {
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    const reloadId = await replaceInstance();

    // The replaced server answers the request that was already on the wire. That
    // reply names its own record, which was sent for a server the identity change
    // dropped, so it is refused whatever identity/epoch the reload re-recorded the
    // key with.
    dispatchMessage(list.reply('old', supersededId));
    await nextTick();

    // Nothing may be written under the id now pointed at the new server: not the
    // rows, and not the cache the next visit would be served from.
    expect(list.stored(state) ?? []).toHaveLength(0);
    expect(list.cached(state)).toBeUndefined();

    // The reload's request is still outstanding — the stale reply consumed the
    // record it named, not the reload's — so its own reply fills the list as usual.
    dispatchMessage(list.reply('new', reloadId));
    await nextTick();

    expect(list.stored(state)).toHaveLength(1);
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(list.cached(state)).toHaveLength(1);
    expect(rowName(list.cached(state))).toBe('new-server-row');
    expect(state.loading.get(list.key)).toBe(false);
  });

  it('drops the replaced server’s reply even when it lands after the reload’s own', async () => {
    // The interleaving the FIFO attribution could not survive: the reload is
    // answered first. Each reply is now judged by the record its id names, so the
    // superseded reply is refused on its own merits instead of consuming the
    // reload's record and writing the replaced server's rows over the fresh ones.
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    const reloadId = await replaceInstance();

    dispatchMessage(list.reply('new', reloadId));
    await nextTick();
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(rowName(list.cached(state))).toBe('new-server-row');

    dispatchMessage(list.reply('old', supersededId));
    await nextTick();

    // The late reply of the replaced server must not overwrite the fresh rows or
    // seed the cache the dashboard would serve the previous server's data from.
    expect(list.stored(state)).toHaveLength(1);
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(list.cached(state)).toHaveLength(1);
    expect(rowName(list.cached(state))).toBe('new-server-row');
  });

  it('attributes a reply to the request it answers, not to the latest record', async () => {
    // What the id rule does that the single-record version could not: the reply is
    // judged by the record of the request it names, so a record sent for a server
    // the instance no longer points at makes the reply stale even when the reload
    // has re-recorded the key with the same identity/epoch. The superseded
    // server's reply is refused and its rows never reach the list.
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    const reloadId = await replaceInstance();

    dispatchMessage(list.reply('old', supersededId));
    await nextTick();
    expect(list.stored(state) ?? []).toHaveLength(0);

    dispatchMessage(list.reply('new', reloadId));
    await nextTick();
    expect(rowName(list.stored(state))).toBe('new-server-row');
  });

  it('keeps the fresh rows when both replies arrive in the host’s send order', async () => {
    // The order the host actually answers in: the request queued first (the
    // server being replaced) is answered first.
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    const reloadId = await replaceInstance();

    dispatchMessage(list.reply('old', supersededId));
    await nextTick();
    dispatchMessage(list.reply('new', reloadId));
    await nextTick();

    expect(list.stored(state)).toHaveLength(1);
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(list.cached(state)).toHaveLength(1);
    expect(rowName(list.cached(state))).toBe('new-server-row');
  });

  it('ignores a reply whose request id is not outstanding, without freeing the slot', async () => {
    const { state } = await createState();
    await startReplacedLoad(state);
    const reloadId = await replaceInstance();
    expect(state.loading.get(list.key)).toBe(true);

    // An id this webview never posted — a reply from a build answering a
    // different request, or one built by hand. It must not write (the id names no
    // request of ours) and must not free the loading slot either: the reload's own
    // request is still outstanding and the slot is waiting for it.
    dispatchMessage(list.reply('old', `${list.key}-never-sent`));
    await nextTick();

    expect(list.stored(state) ?? []).toHaveLength(0);
    expect(list.cached(state)).toBeUndefined();
    expect(state.loading.get(list.key)).toBe(true);

    dispatchMessage(list.reply('new', reloadId));
    await nextTick();

    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(state.loading.get(list.key)).toBe(false);
  });

  it('ignores a duplicate of a reply it already attributed', async () => {
    const { state } = await createState();
    const supersededId = await startReplacedLoad(state);
    const reloadId = await replaceInstance();

    dispatchMessage(list.reply('old', supersededId));
    await nextTick();
    expect(list.stored(state) ?? []).toHaveLength(0);
    expect(state.errors.has(list.key)).toBe(false);

    // The same id again, this time as a failure. Its record was already consumed,
    // so the duplicate names no outstanding request and is dropped — it must not be
    // attributed to the reload's still-outstanding request (which would put the
    // replaced server's failure on the current server's slot) and must not consume
    // that record either, or the reload's own reply would go unattributed.
    dispatchMessage(list.failure('the replaced server failed', supersededId));
    await nextTick();

    expect(state.errors.has(list.key)).toBe(false);
    expect(list.stored(state) ?? []).toHaveLength(0);
    expect(list.cached(state)).toBeUndefined();

    dispatchMessage(list.reply('new', reloadId));
    await nextTick();

    expect(list.stored(state)).toHaveLength(1);
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(state.errors.has(list.key)).toBe(false);
    expect(state.loading.get(list.key)).toBe(false);
  });

  it('still clears the right slot for a failure reply that carries no id', async () => {
    // A host build that predates the echo, or a failure reply sent before the host
    // can echo anything, has to keep working: the webview must not go blind to a
    // failure. With no id to attribute by, the reply falls back to the oldest
    // outstanding record — here the only one, sent for the server still configured
    // — so its error reaches the slot and the spinner clears.
    const { state } = await createState();
    dispatchMessage({ command: 'instances', data: [INSTANCE_A] });
    await nextTick();
    vscodeApiMock.postMessage.mockClear();
    state.loadRepositories(INSTANCE_A.id, true);
    state.loadMyIssues(INSTANCE_A.id, 'open', true);
    state.loadMyPullRequests(INSTANCE_A.id, 'open', true);
    expect(state.loading.get(list.key)).toBe(true);

    dispatchMessage(list.failure('the list failed'));
    await nextTick();

    expect(state.errors.get(list.key)).toBe('the list failed');
    expect(state.loading.get(list.key)).toBe(false);
    expect(list.stored(state) ?? []).toHaveLength(0);
    expect(list.cached(state)).toBeUndefined();
  });

  it('still accepts a reply that answers no recorded request of ours and carries no id', async () => {
    // Hand-built replies — and a reply from a host build that answers a request
    // this webview never recorded — keep flowing when they carry no id, which is
    // the pre-id behaviour. Only a reply that *names* an id this webview has no
    // outstanding request for is dropped.
    const { state } = await createState();
    dispatchMessage({ command: 'instances', data: [INSTANCE_A] });
    await nextTick();

    dispatchMessage(list.reply('new'));
    await nextTick();

    expect(list.stored(state)).toHaveLength(1);
  });

  it('keeps answering a host that sends its reply without the id and then a requestError fallback', async () => {
    // The onboarding panel serves `getRepositories` for the setup guide: its reply
    // carries the handler's shape but no `_requestId`, and its dispatcher then
    // takes the request for unanswered and sends a `requestError` naming the id it
    // never echoed. Neither may be lost — the no-id reply still fills the list (the
    // pre-id attribution) and the late fallback finds its record already consumed,
    // so it is ignored instead of putting a failure on a list that did arrive.
    const { state } = await createState();
    dispatchMessage({ command: 'instances', data: [INSTANCE_A] });
    await nextTick();
    vscodeApiMock.postMessage.mockClear();
    state.loadRepositories(INSTANCE_A.id, true);
    state.loadMyIssues(INSTANCE_A.id, 'open', true);
    state.loadMyPullRequests(INSTANCE_A.id, 'open', true);
    const requestId = listRequestId(list.request.command) as string;
    expect(typeof requestId).toBe('string');

    dispatchMessage(list.reply('new'));
    await nextTick();
    dispatchMessage({
      command: 'requestError',
      _requestId: requestId,
      error: 'The request could not be completed',
    });
    await nextTick();

    expect(list.stored(state)).toHaveLength(1);
    expect(rowName(list.stored(state))).toBe('new-server-row');
    expect(list.cached(state)).toHaveLength(1);
    expect(state.errors.has(list.key)).toBe(false);
    expect(state.loading.get(list.key)).toBe(false);
  });
});
