packages:
  - packages/*
  - tools/*

allowBuilds:
  '@vscode/vsce-sign': true
  es5-ext: true
  esbuild: true
  keytar: true
  lefthook: true
  msw: true

onlyBuiltDependencies:
  - es5-ext
  - esbuild
  - msw
